name: Anindita Basu's website
description: Anindita's professional interests
markdown: kramdown
url: "https://aninditabasu.github.io"
#
remote_theme: just-the-docs/just-the-docs
title: AB's website
baseurl: "/AninditaBasu"
logo: "/images/ab.jpg"
search_enabled: true
search:
  heading_level: 2
  previews: 3
footer_content: "Copyright &copy; 2015-2022 Anindita Basu."
back_to_top: true
back_to_top_text: "Back to top"
plugins:
  - jekyll-seo-tag