# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# internetarchive documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 23 20:16:03 2013.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# At top on conf.py (with other import statements)
import recommonmark
from recommonmark.transform import AutoStructify

# So that the code and version for the ia python library are taken from the latest git version
sys.path.insert(0, os.path.abspath('./internetarchive/'))
import internetarchive
from internetarchive import __version__

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../../'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'recommonmark',
    'sphinx_copybutton',
    'sphinx-favicon',
]

favicons = [
    {
        "rel": "icon",
        "static-file": "logo.jpg",
        "type": "image/jpg",
    },
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

#support markdown .md files
from recommonmark.parser import CommonMarkParser
source_parsers = {
    '.md': CommonMarkParser,
}

# The suffix of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Internet Archive item APIs'
copyright = u'2018-2022, Internet Archive'
author = u'Internet Archive'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    'internetarchive/metadata.rst',  # Now in root. File is there for compatability with readthedocs.io.
    'internetarchive/jq.rst',  # WIP.
]

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_book_theme"
html_copy_source = True

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for this theme, see the
# documentation at https://sphinx-book-theme.readthedocs.io/en/stable/index.html.

html_sidebars = {
    "**": ["sidebar-logo.html", "search-field.html", "sbt-sidebar-nav.html"]
}

html_theme_options = {
    "show_navbar_depth": 2,
    "home_page_in_toc": True,
    "toc_title": "On this page",
    "show_toc_level": 2,
}

html_title = 'Internet Archive Developer Portal'
html_static_path = ['_static']
html_css_files = ['css/custom.css']
html_logo = '_static/Internet Archive Logo.png'

# Output file base name for HTML help builder.
#htmlhelp_basename = 'internetarchivedoc'



# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'internetarchive.tex', 'internetarchive Documentation',
   'Jacob M. Johnson', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'internetarchive', 'internetarchive Documentation',
     ['Jacob M. Johnson'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'internetarchive', 'internetarchive Documentation',
   'Jacob M. Johnson', 'internetarchive', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

#autodoc_member_order = 'bysource'

intersphinx_mapping = {
    'python': ('https://docs.python.org/2.7', None),
    'requests': ('http://docs.python-requests.org/en/latest/', None)
}

def setup(app):
    app.add_config_value('recommonmark_config', dict(), True)
    app.add_transform(AutoStructify)
